// =====================================================================
//  Malum 精魂掉落 - 自定义 API
// ---------------------------------------------------------------------
//  改这里即可。格式：
//    '生物id': { primary: '主精魂id', spirits: [ ['精魂id', 数量], ... ] }
//
//  可用精魂（Malum 全部 9 种）：
//    malum:sacred    神圣
//    malum:wicked    邪恶
//    malum:arcane    奥术
//    malum:eldritch  邪异
//    malum:aerial    风
//    malum:aqueous   水
//    malum:earthen   土
//    malum:infernal  火
//    malum:umbral    影
//
//  这里的生物用的是灾变(L_Ender's Cataclysm)的实体。
//  改完后执行 /reload 即可生效；JEI 里的“精魂收割”需要在client_scripts/spirits_drops_jei.js中同步修改才会正常显示(需要重启客户端)
// =====================================================================
const $BuiltInRegistries = Java.loadClass('net.minecraft.core.registries.BuiltInRegistries')
const SPIRIT_DROPS = {
  'cataclysm:ignis':                   { primary: 'malum:infernal', spirits: [['malum:infernal', 3], ['malum:earthen', 1]] },
  'cataclysm:ignited_berserker':       { primary: 'malum:infernal', spirits: [['malum:infernal', 1]] },
  'cataclysm:ignited_revenant':        { primary: 'malum:infernal', spirits: [['malum:infernal', 1]] },
  'cataclysm:netherite_monstrosity':   { primary: 'malum:earthen',  spirits: [['malum:earthen', 4], ['malum:infernal', 2]] },
  'cataclysm:netherite_ministrosity':  { primary: 'malum:earthen',  spirits: [['malum:earthen', 1]] },
  'cataclysm:the_harbinger':           { primary: 'malum:eldritch', spirits: [['malum:eldritch', 4], ['malum:wicked', 2], ['malum:aerial', 1]] },
  'cataclysm:ender_guardian':          { primary: 'malum:umbral',   spirits: [['malum:umbral', 3], ['malum:eldritch', 2], ['malum:aerial', 1]] },
  'cataclysm:ender_golem':             { primary: 'malum:eldritch', spirits: [['malum:eldritch', 2], ['malum:umbral', 1]] },
  'cataclysm:the_watcher':             { primary: 'malum:umbral',   spirits: [['malum:umbral', 2], ['malum:wicked', 1]] },
  'cataclysm:the_prowler':             { primary: 'malum:wicked',   spirits: [['malum:wicked', 2], ['malum:umbral', 1]] },
  'cataclysm:the_leviathan':           { primary: 'malum:aqueous',  spirits: [['malum:aqueous', 5], ['malum:eldritch', 2], ['malum:sacred', 1]] },
  'cataclysm:the_baby_leviathan':      { primary: 'malum:aqueous',  spirits: [['malum:aqueous', 2]] },
  'cataclysm:scylla':                  { primary: 'malum:aqueous',  spirits: [['malum:aqueous', 3], ['malum:aerial', 1], ['malum:eldritch', 1]] },
  'cataclysm:ancient_remnant':         { primary: 'malum:earthen',  spirits: [['malum:earthen', 3], ['malum:arcane', 2]] },
  'cataclysm:modern_remnant':          { primary: 'malum:earthen',  spirits: [['malum:earthen', 1], ['malum:arcane', 1]] },
  'cataclysm:maledictus':              { primary: 'malum:wicked',   spirits: [['malum:wicked', 2], ['malum:arcane', 1]] },
  'cataclysm:amethyst_crab':           { primary: 'malum:arcane',   spirits: [['malum:arcane', 2], ['malum:aqueous', 1]] },
  'cataclysm:coral_golem':             { primary: 'malum:aqueous',  spirits: [['malum:aqueous', 2], ['malum:earthen', 1]] },
  'cataclysm:coralssus':               { primary: 'malum:aqueous',  spirits: [['malum:aqueous', 2]] },
  'cataclysm:deepling_warlock':        { primary: 'malum:arcane',   spirits: [['malum:arcane', 1], ['malum:aqueous', 1]] },
  'cataclysm:deepling_priest':         { primary: 'malum:sacred',   spirits: [['malum:sacred', 1], ['malum:aqueous', 1]] },
  'cataclysm:cindaria':                { primary: 'malum:sacred',   spirits: [['malum:sacred', 2], ['malum:arcane', 1]] },
  'cataclysm:hippocamtus':             { primary: 'malum:aerial',   spirits: [['malum:aerial', 1], ['malum:sacred', 1]] },
  'cataclysm:kobolediator':            { primary: 'malum:earthen',  spirits: [['malum:earthen', 2]] },
  'cataclysm:koboleton':               { primary: 'malum:earthen',  spirits: [['malum:earthen', 1]] },
  'cataclysm:wadjet':                  { primary: 'malum:earthen',  spirits: [['malum:earthen', 1], ['malum:arcane', 1]] },
  'cataclysm:clawdian':                { primary: 'malum:wicked',   spirits: [['malum:wicked', 1]] },
  'cataclysm:aptrgangr':               { primary: 'malum:umbral',   spirits: [['malum:umbral', 1], ['malum:wicked', 1]] },
  'cataclysm:draugr':                  { primary: 'malum:umbral',   spirits: [['malum:umbral', 1]] },
  'cataclysm:royal_draugr':            { primary: 'malum:umbral',   spirits: [['malum:umbral', 1]] },
  'cataclysm:elite_draugr':            { primary: 'malum:umbral',   spirits: [['malum:umbral', 1]] },
  'cataclysm:endermaptera':            { primary: 'malum:eldritch', spirits: [['malum:eldritch', 1]] },
  'cataclysm:lionfish':                { primary: 'malum:aqueous',  spirits: [['malum:aqueous', 1]] },
  'cataclysm:symbiocto':               { primary: 'malum:aqueous',  spirits: [['malum:aqueous', 1]] },
  'cataclysm:urchinkin':               { primary: 'malum:aqueous',  spirits: [['malum:aqueous', 1]] },
  'cataclysm:drowned_host':            { primary: 'malum:aqueous',  spirits: [['malum:aqueous', 1]] }
}

// 是否把“没在上面定义”的实体的默认精魂掉落全部删除
const DISABLE_DEFAULT_DROPS = true

// =====================================================================
//  以下为自动生成，请勿手动修改
// =====================================================================
const MALUM_DEFAULT_DROPS = [
  ['armadillo', 'minecraft:armadillo'],
  ['axolotl', 'minecraft:axolotl'],
  ['bat', 'minecraft:bat'],
  ['bee', 'minecraft:bee'],
  ['blaze', 'minecraft:blaze'],
  ['bogged', 'minecraft:bogged'],
  ['breeze', 'minecraft:breeze'],
  ['cat', 'minecraft:cat'],
  ['cave_spider', 'minecraft:cave_spider'],
  ['chicken', 'minecraft:chicken'],
  ['cod', 'minecraft:cod'],
  ['cow', 'minecraft:cow'],
  ['creeper', 'minecraft:creeper'],
  ['dolphin', 'minecraft:dolphin'],
  ['donkey', 'minecraft:donkey'],
  ['drowned', 'minecraft:drowned'],
  ['elder_guardian', 'minecraft:elder_guardian'],
  ['enderman', 'minecraft:enderman'],
  ['endermite', 'minecraft:endermite'],
  ['ender_dragon', 'minecraft:ender_dragon'],
  ['evoker', 'minecraft:evoker'],
  ['fox', 'minecraft:fox'],
  ['ghast', 'minecraft:ghast'],
  ['glow_squid', 'minecraft:glow_squid'],
  ['goat', 'minecraft:goat'],
  ['guardian', 'minecraft:guardian'],
  ['hoglin', 'minecraft:hoglin'],
  ['horse', 'minecraft:horse'],
  ['husk', 'minecraft:husk'],
  ['illusioner', 'minecraft:illusioner'],
  ['iron_golem', 'minecraft:iron_golem'],
  ['llama', 'minecraft:llama'],
  ['magma_cube', 'minecraft:magma_cube'],
  ['mooshroom', 'minecraft:mooshroom'],
  ['mule', 'minecraft:mule'],
  ['ocelot', 'minecraft:ocelot'],
  ['panda', 'minecraft:panda'],
  ['parrot', 'minecraft:parrot'],
  ['phantom', 'minecraft:phantom'],
  ['pig', 'minecraft:pig'],
  ['piglin', 'minecraft:piglin'],
  ['piglin_brute', 'minecraft:piglin_brute'],
  ['pillager', 'minecraft:pillager'],
  ['polar_bear', 'minecraft:polar_bear'],
  ['pufferfish', 'minecraft:pufferfish'],
  ['rabbit', 'minecraft:rabbit'],
  ['ravager', 'minecraft:ravager'],
  ['salmon', 'minecraft:salmon'],
  ['sheep', 'minecraft:sheep'],
  ['shulker', 'minecraft:shulker'],
  ['silverfish', 'minecraft:silverfish'],
  ['skeleton', 'minecraft:skeleton'],
  ['skeleton_horse', 'minecraft:skeleton_horse'],
  ['slime', 'minecraft:slime'],
  ['snow_golem', 'minecraft:snow_golem'],
  ['snuffles_snuffle', 'snuffles:snuffle'],
  ['spider', 'minecraft:spider'],
  ['squid', 'minecraft:squid'],
  ['stray', 'minecraft:stray'],
  ['strider', 'minecraft:strider'],
  ['tadpole', 'minecraft:tadpole'],
  ['trader_llama', 'minecraft:trader_llama'],
  ['tropical_fish', 'minecraft:tropical_fish'],
  ['turtle', 'minecraft:turtle'],
  ['vex', 'minecraft:vex'],
  ['villager', 'minecraft:villager'],
  ['vindicator', 'minecraft:vindicator'],
  ['wandering_trader', 'minecraft:wandering_trader'],
  ['witch', 'minecraft:witch'],
  ['wither', 'minecraft:wither'],
  ['wither_skeleton', 'minecraft:wither_skeleton'],
  ['wolf', 'minecraft:wolf'],
  ['zoglin', 'minecraft:zoglin'],
  ['zombie', 'minecraft:zombie'],
  ['zombie_brute', 'eidolon:zombie_brute'],
  ['zombie_horse', 'minecraft:zombie_horse'],
  ['zombie_villager', 'minecraft:zombie_villager'],
  ['zombified_piglin', 'minecraft:zombified_piglin'],
  ['abnormals/atmospheric_cochineal', 'atmospheric:cochineal'],
  ['abnormals/autumnity_snail', 'autumnity:snail'],
  ['abnormals/autumnity_turkey', 'autumnity:turkey'],
  ['abnormals/buzzier_bees_moobloom', 'buzzier_bees:moobloom'],
  ['abnormals/caverns_and_chasms_deeper', 'caverns_and_chasms:deeper'],
  ['abnormals/caverns_and_chasms_glare', 'caverns_and_chasms:glare'],
  ['abnormals/caverns_and_chasms_mime', 'caverns_and_chasms:mime'],
  ['abnormals/caverns_and_chasms_peeper', 'caverns_and_chasms:peeper'],
  ['abnormals/endergetic_booflo', 'endergetic:booflo'],
  ['abnormals/endergetic_booflo_adolescent', 'endergetic:booflo_adolescent'],
  ['abnormals/endergetic_booflo_baby', 'endergetic:booflo_baby'],
  ['abnormals/endergetic_puff_bug', 'endergetic:puff_bug'],
  ['abnormals/environmental_deer', 'environmental:deer'],
  ['abnormals/environmental_duck', 'environmental:duck'],
  ['abnormals/environmental_koi', 'environmental:koi'],
  ['abnormals/environmental_reindeer', 'environmental:reindeer'],
  ['abnormals/environmental_slabfish', 'environmental:slabfish'],
  ['abnormals/environmental_tapir', 'environmental:tapir'],
  ['abnormals/environmental_yak', 'environmental:yak'],
  ['abnormals/environmental_zebra', 'environmental:zebra'],
  ['abnormals/neapolitan_chimpanzee', 'neapolitan:chimpanzee'],
  ['abnormals/neapolitan_plantain_spider', 'neapolitan:plantain_spider'],
  ['abnormals/savage_and_ravage_creepie', 'savage_and_ravage:creepie'],
  ['abnormals/savage_and_ravage_executioner', 'savage_and_ravage:executioner'],
  ['abnormals/savage_and_ravage_griefer', 'savage_and_ravage:griefer'],
  ['abnormals/savage_and_ravage_iceologer', 'savage_and_ravage:iceologer'],
  ['abnormals/savage_and_ravage_skeleton_villager', 'savage_and_ravage:skeleton_villager'],
  ['abnormals/upgrade_aquatic_flare', 'upgrade_aquatic:flare'],
  ['abnormals/upgrade_aquatic_goose', 'upgrade_aquatic:goose'],
  ['abnormals/upgrade_aquatic_great_thrasher', 'upgrade_aquatic:great_thrasher'],
  ['abnormals/upgrade_aquatic_lionfish', 'upgrade_aquatic:lionfish'],
  ['abnormals/upgrade_aquatic_nautilus', 'upgrade_aquatic:nautilus'],
  ['abnormals/upgrade_aquatic_perch', 'upgrade_aquatic:perch'],
  ['abnormals/upgrade_aquatic_pike', 'upgrade_aquatic:pike'],
  ['abnormals/upgrade_aquatic_thrasher', 'upgrade_aquatic:thrasher'],
  ['alexs_mobs/alexsmobs_alligator_snapping_turtle', 'alexsmobs:alligator_snapping_turtle'],
  ['alexs_mobs/alexsmobs_anaconda', 'alexsmobs:anaconda'],
  ['alexs_mobs/alexsmobs_anteater', 'alexsmobs:anteater'],
  ['alexs_mobs/alexsmobs_bald_eagle', 'alexsmobs:bald_eagle'],
  ['alexs_mobs/alexsmobs_bison', 'alexsmobs:bison'],
  ['alexs_mobs/alexsmobs_blobfish', 'alexsmobs:blobfish'],
  ['alexs_mobs/alexsmobs_bone_serpent', 'alexsmobs:bone_serpent'],
  ['alexs_mobs/alexsmobs_bunfungus', 'alexsmobs:bunfungus'],
  ['alexs_mobs/alexsmobs_cachalot_whale', 'alexsmobs:cachalot_whale'],
  ['alexs_mobs/alexsmobs_capuchin_monkey', 'alexsmobs:capuchin_monkey'],
  ['alexs_mobs/alexsmobs_centipede', 'alexsmobs:centipede_head'],
  ['alexs_mobs/alexsmobs_cockroach', 'alexsmobs:cockroach'],
  ['alexs_mobs/alexsmobs_comb_jelly', 'alexsmobs:comb_jelly'],
  ['alexs_mobs/alexsmobs_cosmaw', 'alexsmobs:cosmaw'],
  ['alexs_mobs/alexsmobs_cosmic_cod', 'alexsmobs:cosmic_cod'],
  ['alexs_mobs/alexsmobs_crimson_mosquito', 'alexsmobs:crimson_mosquito'],
  ['alexs_mobs/alexsmobs_crocodile', 'alexsmobs:crocodile'],
  ['alexs_mobs/alexsmobs_crow', 'alexsmobs:crow'],
  ['alexs_mobs/alexsmobs_dropbear', 'alexsmobs:dropbear'],
  ['alexs_mobs/alexsmobs_elephant', 'alexsmobs:elephant'],
  ['alexs_mobs/alexsmobs_emu', 'alexsmobs:emu'],
  ['alexs_mobs/alexsmobs_endergrade', 'alexsmobs:endergrade'],
  ['alexs_mobs/alexsmobs_enderiophage', 'alexsmobs:enderiophage'],
  ['alexs_mobs/alexsmobs_flutter', 'alexsmobs:flutter'],
  ['alexs_mobs/alexsmobs_fly', 'alexsmobs:fly'],
  ['alexs_mobs/alexsmobs_frilled_shark', 'alexsmobs:frilled_shark'],
  ['alexs_mobs/alexsmobs_froststalker', 'alexsmobs:froststalker'],
  ['alexs_mobs/alexsmobs_gazelle', 'alexsmobs:gazelle'],
  ['alexs_mobs/alexsmobs_gelada_monkey', 'alexsmobs:gelada_monkey'],
  ['alexs_mobs/alexsmobs_giant_squid', 'alexsmobs:giant_squid'],
  ['alexs_mobs/alexsmobs_gorilla', 'alexsmobs:gorilla'],
  ['alexs_mobs/alexsmobs_grizzly_bear', 'alexsmobs:grizzly_bear'],
  ['alexs_mobs/alexsmobs_guster', 'alexsmobs:guster'],
  ['alexs_mobs/alexsmobs_hammerhead_shark', 'alexsmobs:hammerhead_shark'],
  ['alexs_mobs/alexsmobs_hummingbird', 'alexsmobs:hummingbird'],
  ['alexs_mobs/alexsmobs_jerboa', 'alexsmobs:jerboa'],
  ['alexs_mobs/alexsmobs_kangaroo', 'alexsmobs:kangaroo'],
  ['alexs_mobs/alexsmobs_komodo_dragon', 'alexsmobs:komodo_dragon'],
  ['alexs_mobs/alexsmobs_laviathan', 'alexsmobs:laviathan'],
  ['alexs_mobs/alexsmobs_leafcutter_ant', 'alexsmobs:leafcutter_ant'],
  ['alexs_mobs/alexsmobs_lobster', 'alexsmobs:lobster'],
  ['alexs_mobs/alexsmobs_maned_wolf', 'alexsmobs:maned_wolf'],
  ['alexs_mobs/alexsmobs_mantis_shrimp', 'alexsmobs:mantis_shrimp'],
  ['alexs_mobs/alexsmobs_mimicube', 'alexsmobs:mimicube'],
  ['alexs_mobs/alexsmobs_mimic_octopus', 'alexsmobs:mimic_octopus'],
  ['alexs_mobs/alexsmobs_moose', 'alexsmobs:moose'],
  ['alexs_mobs/alexsmobs_mungus', 'alexsmobs:mungus'],
  ['alexs_mobs/alexsmobs_orca', 'alexsmobs:orca'],
  ['alexs_mobs/alexsmobs_platypus', 'alexsmobs:platypus'],
  ['alexs_mobs/alexsmobs_raccoon', 'alexsmobs:raccoon'],
  ['alexs_mobs/alexsmobs_rattlesnake', 'alexsmobs:rattlesnake'],
  ['alexs_mobs/alexsmobs_roadrunner', 'alexsmobs:roadrunner'],
  ['alexs_mobs/alexsmobs_rocky_roller', 'alexsmobs:rocky_roller'],
  ['alexs_mobs/alexsmobs_seagull', 'alexsmobs:seagull'],
  ['alexs_mobs/alexsmobs_seal', 'alexsmobs:seal'],
  ['alexs_mobs/alexsmobs_shoebill', 'alexsmobs:shoebill'],
  ['alexs_mobs/alexsmobs_snow_leopard', 'alexsmobs:snow_leopard'],
  ['alexs_mobs/alexsmobs_soul_vulture', 'alexsmobs:soul_vulture'],
  ['alexs_mobs/alexsmobs_spectre', 'alexsmobs:spectre'],
  ['alexs_mobs/alexsmobs_straddler', 'alexsmobs:straddler'],
  ['alexs_mobs/alexsmobs_stradpole', 'alexsmobs:stradpole'],
  ['alexs_mobs/alexsmobs_sunbird', 'alexsmobs:sunbird'],
  ['alexs_mobs/alexsmobs_tarantula_hawk', 'alexsmobs:tarantula_hawk'],
  ['alexs_mobs/alexsmobs_tasmanian_devil', 'alexsmobs:tasmanian_devil'],
  ['alexs_mobs/alexsmobs_terrapin', 'alexsmobs:terrapin'],
  ['alexs_mobs/alexsmobs_tiger', 'alexsmobs:tiger'],
  ['alexs_mobs/alexsmobs_toucan', 'alexsmobs:toucan'],
  ['alexs_mobs/alexsmobs_tusklin', 'alexsmobs:tusklin'],
  ['alexs_mobs/alexsmobs_void_worm', 'alexsmobs:void_worm'],
  ['alexs_mobs/alexsmobs_warped_mosco', 'alexsmobs:warped_mosco'],
  ['alexs_mobs/alexsmobs_warped_toad', 'alexsmobs:warped_toad'],
  ['aquaculture/arapaima', 'aquaculture:arapaima'],
  ['aquaculture/arrau_turtle', 'aquaculture:arrau_turtle'],
  ['aquaculture/atlantic_cod', 'aquaculture:atlantic_cod'],
  ['aquaculture/atlantic_halibut', 'aquaculture:atlantic_halibut'],
  ['aquaculture/atlantic_herring', 'aquaculture:atlantic_herring'],
  ['aquaculture/bayad', 'aquaculture:bayad'],
  ['aquaculture/blackfish', 'aquaculture:blackfish'],
  ['aquaculture/bluegill', 'aquaculture:bluegill'],
  ['aquaculture/boulti', 'aquaculture:boulti'],
  ['aquaculture/box_turtle', 'aquaculture:box_turtle'],
  ['aquaculture/brown_shrooma', 'aquaculture:brown_shrooma'],
  ['aquaculture/brown_trout', 'aquaculture:brown_trout'],
  ['aquaculture/capitaine', 'aquaculture:capitaine'],
  ['aquaculture/carp', 'aquaculture:carp'],
  ['aquaculture/catfish', 'aquaculture:catfish'],
  ['aquaculture/gar', 'aquaculture:gar'],
  ['aquaculture/jellyfish', 'aquaculture:jellyfish'],
  ['aquaculture/minnow', 'aquaculture:minnow'],
  ['aquaculture/muskellunge', 'aquaculture:muskellunge'],
  ['aquaculture/pacific_halibut', 'aquaculture:pacific_halibut'],
  ['aquaculture/perch', 'aquaculture:perch'],
  ['aquaculture/pink_salmon', 'aquaculture:pink_salmon'],
  ['aquaculture/piranha', 'aquaculture:piranha'],
  ['aquaculture/pollock', 'aquaculture:pollock'],
  ['aquaculture/rainbow_trout', 'aquaculture:rainbow_trout'],
  ['aquaculture/red_grouper', 'aquaculture:red_grouper'],
  ['aquaculture/red_shrooma', 'aquaculture:red_shrooma'],
  ['aquaculture/smallmouth_bass', 'aquaculture:smallmouth_bass'],
  ['aquaculture/starshell_turtle', 'aquaculture:starshell_turtle'],
  ['aquaculture/synodontis', 'aquaculture:synodontis'],
  ['aquaculture/tambaqui', 'aquaculture:tambaqui'],
  ['aquaculture/tuna', 'aquaculture:tuna'],
  ['betterend/cubozoa', 'betterend:cubozoa'],
  ['betterend/dragonfly', 'betterend:dragonfly'],
  ['betterend/end_fish', 'betterend:end_fish'],
  ['betterend/end_slime', 'betterend:end_slime'],
  ['betterend/shadow_walker', 'betterend:shadow_walker'],
  ['betterend/silk_moth', 'betterend:silk_moth'],
  ['born_in_chaos/baby_skeleton', 'born_in_chaos_v1:baby_skeleton'],
  ['born_in_chaos/baby_spider', 'born_in_chaos_v1:baby_spider'],
  ['born_in_chaos/barrel_zombie', 'born_in_chaos_v1:barrel_zombie'],
  ['born_in_chaos/bloody_gadfly', 'born_in_chaos_v1:bloody_gadfly'],
  ['born_in_chaos/bonescaller', 'born_in_chaos_v1:bonescaller'],
  ['born_in_chaos/bone_imp', 'born_in_chaos_v1:bone_imp'],
  ['born_in_chaos/corpse_fish', 'born_in_chaos_v1:corpse_fish'],
  ['born_in_chaos/corpse_fly', 'born_in_chaos_v1:corpse_fly'],
  ['born_in_chaos/corpse_maggot', 'born_in_chaos_v1:corpse_maggot'],
  ['born_in_chaos/dark_vortex', 'born_in_chaos_v1:dark_vortex'],
  ['born_in_chaos/decaying_zombie', 'born_in_chaos_v1:decaying_zombie'],
  ['born_in_chaos/decrepit_skeleton', 'born_in_chaos_v1:decrepit_skeleton'],
  ['born_in_chaos/diamond_termite', 'born_in_chaos_v1:diamond_termite'],
  ['born_in_chaos/dire_hound_leader', 'born_in_chaos_v1:dire_hound_leader'],
  ['born_in_chaos/door_knight', 'born_in_chaos_v1:door_knight'],
  ['born_in_chaos/dread_hound', 'born_in_chaos_v1:dread_hound'],
  ['born_in_chaos/fallen_chaos_knight', 'born_in_chaos_v1:fallen_chaos_knight'],
  ['born_in_chaos/firelight', 'born_in_chaos_v1:firelight'],
  ['born_in_chaos/glutton_fish', 'born_in_chaos_v1:glutton_fish'],
  ['born_in_chaos/infernal_spirit', 'born_in_chaos_v1:infernal_spirit'],
  ['born_in_chaos/krampus', 'born_in_chaos_v1:krampus'],
  ['born_in_chaos/krampus_henchman', 'born_in_chaos_v1:krampus_henchman'],
  ['born_in_chaos/lifestealer', 'born_in_chaos_v1:lifestealer'],
  ['born_in_chaos/lords_felsteed', 'born_in_chaos_v1:lords_felsteed'],
  ['born_in_chaos/lord_pumpkinhead_head', 'born_in_chaos_v1:lord_pumpkinhead_head'],
  ['born_in_chaos/lord_the_headless', 'born_in_chaos_v1:lord_the_headless'],
  ['born_in_chaos/missionary', 'born_in_chaos_v1:missionary'],
  ['born_in_chaos/mother_spider', 'born_in_chaos_v1:mother_spider'],
  ['born_in_chaos/nightmare_stalker', 'born_in_chaos_v1:nightmare_stalker'],
  ['born_in_chaos/phantom_creeper_copy', 'born_in_chaos_v1:phantom_creeper_copy'],
  ['born_in_chaos/pumpkin_spirit', 'born_in_chaos_v1:pumpkin_spirit'],
  ['born_in_chaos/restless_spirit', 'born_in_chaos_v1:restless_spirit'],
  ['born_in_chaos/scarlet_persecutor', 'born_in_chaos_v1:scarlet_persecutor'],
  ['born_in_chaos/seared_spirit', 'born_in_chaos_v1:seared_spirit'],
  ['born_in_chaos/senor_pumpkin', 'born_in_chaos_v1:senor_pumpkin'],
  ['born_in_chaos/siamese_skeleton', 'born_in_chaos_v1:siamese_skeleton'],
  ['born_in_chaos/sir_pumpkin', 'born_in_chaos_v1:sir_pumpkin'],
  ['born_in_chaos/sir_pumpkinhead', 'born_in_chaos_v1:sir_pumpkinhead'],
  ['born_in_chaos/skeleton_demoman', 'born_in_chaos_v1:skeleton_demoman'],
  ['born_in_chaos/skeleton_thrasher', 'born_in_chaos_v1:skeleton_thrasher'],
  ['born_in_chaos/skeleton_thrasher_not_despawn', 'born_in_chaos_v1:skeleton_thrasher_not_despawn'],
  ['born_in_chaos/spiritof_chaos', 'born_in_chaos_v1:spiritof_chaos'],
  ['born_in_chaos/spirit_guide', 'born_in_chaos_v1:spirit_guide'],
  ['born_in_chaos/supreme_bonescaller', 'born_in_chaos_v1:supreme_bonescaller'],
  ['born_in_chaos/swarmer', 'born_in_chaos_v1:swarmer'],
  ['born_in_chaos/thornshell_crab', 'born_in_chaos_v1:thornshell_crab'],
  ['born_in_chaos/zombie_bruiser', 'born_in_chaos_v1:zombie_bruiser'],
  ['born_in_chaos/zombie_clown', 'born_in_chaos_v1:zombie_clown'],
  ['born_in_chaos/zombie_fisherman', 'born_in_chaos_v1:zombie_fisherman'],
  ['born_in_chaos/zombie_lumberjack', 'born_in_chaos_v1:zombie_lumberjack'],
  ['bosses_of_mass_destruction/gauntlet', 'bosses_of_mass_destruction:gauntlet'],
  ['bosses_of_mass_destruction/lich', 'bosses_of_mass_destruction:lich'],
  ['bosses_of_mass_destruction/obsidilith', 'bosses_of_mass_destruction:obsidilith'],
  ['bosses_of_mass_destruction/void_blossom', 'bosses_of_mass_destruction:void_blossom'],
  ['botania/gaia_guardian', 'botania:doppleganger'],
  ['botania/pink_wither', 'botania:pink_wither'],
  ['cnb/cactem', 'cnb:cactem'],
  ['cnb/cindershell', 'cnb:cindershell'],
  ['cnb/end_whale', 'cnb:end_whale'],
  ['cnb/lilytad', 'cnb:lilytad'],
  ['cnb/little_grebe', 'cnb:little_grebe'],
  ['cnb/lizard', 'cnb:lizard'],
  ['cnb/minipad', 'cnb:minipad'],
  ['cnb/sporeling', 'cnb:sporeling'],
  ['cnb/yeti', 'cnb:yeti'],
  ['conjurer_illager/conjurer', 'conjurer_illager:conjurer'],
  ['creeperoverhaul/badlands_creeper', 'creeperoverhaul:badlands_creeper'],
  ['creeperoverhaul/bamboo_creeper', 'creeperoverhaul:bamboo_creeper'],
  ['creeperoverhaul/beach_creeper', 'creeperoverhaul:beach_creeper'],
  ['creeperoverhaul/cave_creeper', 'creeperoverhaul:cave_creeper'],
  ['creeperoverhaul/dark_oak_creeper', 'creeperoverhaul:dark_oak_creeper'],
  ['creeperoverhaul/desert_creeper', 'creeperoverhaul:desert_creeper'],
  ['creeperoverhaul/dripstone_creeper', 'creeperoverhaul:dripstone_creeper'],
  ['creeperoverhaul/hills_creeper', 'creeperoverhaul:hills_creeper'],
  ['creeperoverhaul/jungle_creeper', 'creeperoverhaul:jungle_creeper'],
  ['creeperoverhaul/mushroom_creeper', 'creeperoverhaul:mushroom_creeper'],
  ['creeperoverhaul/savannah_creeper', 'creeperoverhaul:savannah_creeper'],
  ['creeperoverhaul/snowy_creeper', 'creeperoverhaul:snowy_creeper'],
  ['creeperoverhaul/spruce_creeper', 'creeperoverhaul:spruce_creeper'],
  ['creeperoverhaul/swamp_creeper', 'creeperoverhaul:swamp_creeper'],
  ['duckling/duck', 'duckling:duck'],
  ['duckling/quackling', 'duckling:quackling'],
  ['earth/carboranea', 'earth:carboranea'],
  ['earth/pertilyo', 'earth:pertilyo'],
  ['earth/rubro', 'earth:rubro'],
  ['ecologics/ecologics_coconut_crab', 'ecologics:coconut_crab'],
  ['eidolon/eidolon_necromancer', 'eidolon:necromancer'],
  ['eidolon/eidolon_raven', 'eidolon:raven'],
  ['eidolon/eidolon_slimy_slug', 'eidolon:slimy_slug'],
  ['eidolon/eidolon_wraith', 'eidolon:wraith'],
  ['enchantwithmob/mob_enchanter', 'enchantwithmob:enchanter'],
  ['endermanoverhaul/badlands_enderman', 'endermanoverhaul:badlands_enderman'],
  ['endermanoverhaul/cave_enderman', 'endermanoverhaul:cave_enderman'],
  ['endermanoverhaul/coral_enderman', 'endermanoverhaul:coral_enderman'],
  ['endermanoverhaul/crimson_forest_enderman', 'endermanoverhaul:crimson_forest_enderman'],
  ['endermanoverhaul/dark_oak_enderman', 'endermanoverhaul:dark_oak_enderman'],
  ['endermanoverhaul/desert_enderman', 'endermanoverhaul:desert_enderman'],
  ['endermanoverhaul/end_enderman', 'endermanoverhaul:end_enderman'],
  ['endermanoverhaul/end_islands_enderman', 'endermanoverhaul:end_islands_enderman'],
  ['endermanoverhaul/flower_fields_enderman', 'endermanoverhaul:flower_fields_enderman'],
  ['endermanoverhaul/ice_spikes_enderman', 'endermanoverhaul:ice_spikes_enderman'],
  ['endermanoverhaul/mushroom_fields_enderman', 'endermanoverhaul:mushroom_fields_enderman'],
  ['endermanoverhaul/nether_wastes_enderman', 'endermanoverhaul:nether_wastes_enderman'],
  ['endermanoverhaul/savanna_enderman', 'endermanoverhaul:savanna_enderman'],
  ['endermanoverhaul/scarab', 'endermanoverhaul:scarab'],
  ['endermanoverhaul/snowy_enderman', 'endermanoverhaul:snowy_enderman'],
  ['endermanoverhaul/soulsand_valley_enderman', 'endermanoverhaul:soulsand_valley_enderman'],
  ['endermanoverhaul/spirit', 'endermanoverhaul:spirit'],
  ['endermanoverhaul/swamp_enderman', 'endermanoverhaul:swamp_enderman'],
  ['endermanoverhaul/warped_forest_enderman', 'endermanoverhaul:warped_forest_enderman'],
  ['endermanoverhaul/windswept_hills_enderman', 'endermanoverhaul:windswept_hills_enderman'],
  ['friendsandfoes/copper_golem', 'friendsandfoes:copper_golem'],
  ['friendsandfoes/glare', 'friendsandfoes:glare'],
  ['friendsandfoes/iceologer', 'friendsandfoes:iceologer'],
  ['friendsandfoes/mauler', 'friendsandfoes:mauler'],
  ['friendsandfoes/moobloom', 'friendsandfoes:moobloom'],
  ['goated/geep', 'goated:geep'],
  ['goblintraders/goblintraders_goblin_trader', 'goblintraders:goblin_trader'],
  ['goblintraders/goblintraders_vein_goblin_trader', 'goblintraders:vein_goblin_trader'],
  ['goety/apostle', 'goety:apostle'],
  ['goety/bear_servant', 'goety:bear_servant'],
  ['goety/blackguard_servant', 'goety:blackguard_servant'],
  ['goety/black_beast', 'goety:black_beast'],
  ['goety/black_wolf', 'goety:black_wolf'],
  ['goety/blaze_servant', 'goety:blaze_servant'],
  ['goety/bone_lord', 'goety:bone_lord'],
  ['goety/bone_spider', 'goety:bone_spider'],
  ['goety/bone_spider_servant', 'goety:bone_spider_servant'],
  ['goety/border_wraith', 'goety:border_wraith'],
  ['goety/border_wraith_servant', 'goety:border_wraith_servant'],
  ['goety/bound_evoker', 'goety:bound_evoker'],
  ['goety/bound_iceologer', 'goety:bound_iceologer'],
  ['goety/cairn_necromancer', 'goety:cairn_necromancer'],
  ['goety/cairn_necromancer_servant', 'goety:cairn_necromancer_servant'],
  ['goety/carrion_maggot', 'goety:carrion_maggot'],
  ['goety/cave_spider_servant', 'goety:cave_spider_servant'],
  ['goety/conquillager', 'goety:conquillager'],
  ['goety/crone', 'goety:crone'],
  ['goety/crusher', 'goety:crusher'],
  ['goety/cryologer', 'goety:cryologer'],
  ['goety/crypt_slime', 'goety:crypt_slime'],
  ['goety/crypt_slime_servant', 'goety:crypt_slime_servant'],
  ['goety/drowned_servant', 'goety:drowned_servant'],
  ['goety/envioker', 'goety:envioker'],
  ['goety/frozen_zombie_servant', 'goety:frozen_zombie_servant'],
  ['goety/ghast_servant', 'goety:ghast_servant'],
  ['goety/grave_golem', 'goety:grave_golem'],
  ['goety/haunt', 'goety:haunt'],
  ['goety/haunted_armor', 'goety:haunted_armor'],
  ['goety/haunted_skull', 'goety:haunted_skull'],
  ['goety/heretic', 'goety:heretic'],
  ['goety/hoglin_servant', 'goety:hoglin_servant'],
  ['goety/hostile_black_wolf', 'goety:hostile_black_wolf'],
  ['goety/husk_servant', 'goety:husk_servant'],
  ['goety/ice_golem', 'goety:ice_golem'],
  ['goety/icy_spider_servant', 'goety:icy_spider_servant'],
  ['goety/inferno', 'goety:inferno'],
  ['goety/inquillager', 'goety:inquillager'],
  ['goety/irk', 'goety:irk'],
  ['goety/jungle_zombie_servant', 'goety:jungle_zombie_servant'],
  ['goety/leapleaf', 'goety:leapleaf'],
  ['goety/magma_cube_servant', 'goety:magma_cube_servant'],
  ['goety/malghast', 'goety:malghast'],
  ['goety/maverick', 'goety:maverick'],
  ['goety/minister', 'goety:minister'],
  ['goety/mini_ghast', 'goety:mini_ghast'],
  ['goety/mossy_skeleton_servant', 'goety:mossy_skeleton_servant'],
  ['goety/necromancer_servant', 'goety:necromancer_servant'],
  ['goety/obsidian_monolith', 'goety:obsidian_monolith'],
  ['goety/piker', 'goety:piker'],
  ['goety/poison_anemone', 'goety:poison_anemone'],
  ['goety/poison_quill_vine', 'goety:poison_quill_vine'],
  ['goety/polar_bear_servant', 'goety:polar_bear_servant'],
  ['goety/preacher', 'goety:preacher'],
  ['goety/quick_growing_kelp', 'goety:quick_growing_kelp'],
  ['goety/quick_growing_vine', 'goety:quick_growing_vine'],
  ['goety/redstone_cube', 'goety:redstone_cube'],
  ['goety/redstone_golem', 'goety:redstone_golem'],
  ['goety/redstone_monstrosity', 'goety:redstone_monstrosity'],
  ['goety/ripper', 'goety:ripper'],
  ['goety/skeleton_pillager', 'goety:skeleton_pillager'],
  ['goety/skeleton_servant', 'goety:skeleton_servant'],
  ['goety/skull_lord', 'goety:skull_lord'],
  ['goety/slime_servant', 'goety:slime_servant'],
  ['goety/spider_servant', 'goety:spider_servant'],
  ['goety/squall_golem', 'goety:squall_golem'],
  ['goety/storm_caster', 'goety:storm_caster'],
  ['goety/stray_servant', 'goety:stray_servant'],
  ['goety/sunken_skeleton_servant', 'goety:sunken_skeleton_servant'],
  ['goety/tormentor', 'goety:tormentor'],
  ['goety/trampler', 'goety:trampler'],
  ['goety/vampire_bat', 'goety:vampire_bat'],
  ['goety/vanguard_servant', 'goety:vanguard_servant'],
  ['goety/vizier', 'goety:vizier'],
  ['goety/warlock', 'goety:warlock'],
  ['goety/wartling', 'goety:wartling'],
  ['goety/wavewhisperer', 'goety:wavewhisperer'],
  ['goety/web_spider_servant', 'goety:web_spider_servant'],
  ['goety/whisperer', 'goety:whisperer'],
  ['goety/wight', 'goety:wight'],
  ['goety/wildfire', 'goety:wildfire'],
  ['goety/wither_necromancer', 'goety:wither_necromancer'],
  ['goety/wither_skeleton_servant', 'goety:wither_skeleton_servant'],
  ['goety/wraith', 'goety:wraith'],
  ['goety/wraith_servant', 'goety:wraith_servant'],
  ['goety/zombie_servant', 'goety:zombie_servant'],
  ['goety/zombie_vindicator', 'goety:zombie_vindicator'],
  ['goety/zpiglin_brute_servant', 'goety:zpiglin_brute_servant'],
  ['goety/zpiglin_servant', 'goety:zpiglin_servant'],
  ['graveyard/acolyte', 'graveyard:acolyte'],
  ['graveyard/corrupted_pillager', 'graveyard:corrupted_pillager'],
  ['graveyard/corrupted_vindicator', 'graveyard:corrupted_vindicator'],
  ['graveyard/ghoul', 'graveyard:ghoul'],
  ['graveyard/nightmare', 'graveyard:nightmare'],
  ['graveyard/reaper', 'graveyard:reaper'],
  ['graveyard/revenant', 'graveyard:revenant'],
  ['graveyard/skeleton_creeper', 'graveyard:skeleton_creeper'],
  ['graveyard/wraith', 'graveyard:wraith'],
  ['guardvillagers/guard', 'guardvillagers:guard'],
  ['habitat/habitat_passerine', 'habitat:passerine'],
  ['habitat/habitat_pooka', 'habitat:pooka'],
  ['hexerei/crow', 'hexerei:crow'],
  ['humancompanions/arbalist', 'humancompanions:arbalist'],
  ['humancompanions/archer', 'humancompanions:archer'],
  ['humancompanions/knight', 'humancompanions:knight'],
  ['hunterillager/hunterillager', 'hunterillager:hunterillager'],
  ['irons_spellbooks/apothecarist', 'irons_spellbooks:apothecarist'],
  ['irons_spellbooks/archevoker', 'irons_spellbooks:archevoker'],
  ['irons_spellbooks/citadel_keeper', 'irons_spellbooks:citadel_keeper'],
  ['irons_spellbooks/cryomancer', 'irons_spellbooks:cryomancer'],
  ['irons_spellbooks/dead_king_corpse', 'irons_spellbooks:dead_king_corpse'],
  ['irons_spellbooks/necromancer', 'irons_spellbooks:necromancer'],
  ['irons_spellbooks/priest', 'irons_spellbooks:priest'],
  ['irons_spellbooks/pyromancer', 'irons_spellbooks:infernal'],
  ['irons_spellbooks/wisp', 'irons_spellbooks:wisp'],
  ['kobolds/kobold', 'kobolds:kobold'],
  ['kobolds/kobold_captain', 'kobolds:kobold_captain'],
  ['kobolds/kobold_child', 'kobolds:kobold_child'],
  ['kobolds/kobold_enchanter', 'kobolds:kobold_enchanter'],
  ['kobolds/kobold_engineer', 'kobolds:kobold_engineer'],
  ['kobolds/kobold_pirate', 'kobolds:kobold_pirate'],
  ['kobolds/kobold_skeleton', 'kobolds:kobold_skeleton'],
  ['kobolds/kobold_warrior', 'kobolds:kobold_warrior'],
  ['kobolds/kobold_zombie', 'kobolds:kobold_zombie'],
  ['kobolds/kobold_zombie_drowned', 'kobolds:kobold_zombie_drowned'],
  ['magicfungi/morbus_mooshroom', 'magicfungi:morbus_mooshroom'],
  ['malum/altar', 'malum:altar'],
  ['malum/believer', 'malum:believer'],
  ['malum/cardinal', 'malum:cardinal'],
  ['malum/cherub', 'malum:cherub'],
  ['malum/evangelist', 'malum:evangelist'],
  ['mowziesmobs/ferrous_wroughtnaught', 'mowziesmobs:ferrous_wroughtnaught'],
  ['mowziesmobs/foliaath', 'mowziesmobs:foliaath'],
  ['mowziesmobs/frostmaw', 'mowziesmobs:frostmaw'],
  ['mowziesmobs/grottol', 'mowziesmobs:grottol'],
  ['mowziesmobs/lantern', 'mowziesmobs:lantern'],
  ['mowziesmobs/naga', 'mowziesmobs:naga'],
  ['mowziesmobs/umvuthana', 'mowziesmobs:umvuthana'],
  ['mowziesmobs/umvuthana_crane', 'mowziesmobs:umvuthana_crane'],
  ['mowziesmobs/umvuthana_raptor', 'mowziesmobs:umvuthana_raptor'],
  ['mowziesmobs/umvuthi', 'mowziesmobs:umvuthi'],
  ['natural_decoration/little_marsh_tit', 'natural_decoration:little_marsh_tit'],
  ['natural_decoration/little_red_breasted_blackbird', 'natural_decoration:little_red_breasted_blackbird'],
  ['natural_decoration/little_robin', 'natural_decoration:little_robin'],
  ['natural_decoration/little_sparrow', 'natural_decoration:little_sparrow'],
  ['natural_decoration/little_swallow', 'natural_decoration:little_swallow'],
  ['natural_decoration/small_snails', 'natural_decoration:small_snails'],
  ['netherexp/apparition', 'netherexp:apparition'],
  ['netherexp/banshee', 'netherexp:banshee'],
  ['netherexp/ecto_slab', 'netherexp:ecto_slab'],
  ['netherexp/stampede', 'netherexp:stampede'],
  ['netherexp/vessel', 'netherexp:vessel'],
  ['netherexp/wisp', 'netherexp:wisp'],
  ['nomansland/billhook_bass', 'nomansland:billhook_bass'],
  ['nomansland/deer', 'nomansland:deer'],
  ['nomansland/goose', 'nomansland:goose'],
  ['nomansland/tortoise', 'nomansland:tortoise'],
  ['progressivebosses/larva', 'progressivebosses:larva'],
  ['progressivebosses/wither_minion', 'progressivebosses:wither_minion'],
  ['quark/quark_crab', 'quark:crab'],
  ['quark/quark_forgotten', 'quark:forgotten'],
  ['quark/quark_foxhound', 'quark:foxhound'],
  ['quark/quark_frog', 'quark:frog'],
  ['quark/quark_shiba', 'quark:shiba'],
  ['quark/quark_stoneling', 'quark:stoneling'],
  ['quark/quark_toretoise', 'quark:toretoise'],
  ['quark/quark_wraith', 'quark:wraith'],
  ['roots/beetle', 'roots:beetle'],
  ['roots/deer', 'roots:deer'],
  ['roots/duck', 'roots:duck'],
  ['roots/fennec', 'roots:fennec'],
  ['roots/green_sprout', 'roots:green_sprout'],
  ['roots/melody_sprout', 'roots:melody_sprout'],
  ['roots/owl', 'roots:owl'],
  ['roots/purple_sprout', 'roots:purple_sprout'],
  ['roots/red_sprout', 'roots:red_sprout'],
  ['roots/snow_sprout', 'roots:snow_sprout'],
  ['roots/tan_sprout', 'roots:tan_sprout'],
  ['snow_pig/snowpig_snow_pig', 'snowpig:snow_pig'],
  ['specialmobs/abyssaldrowned', 'specialmobs:abyssaldrowned'],
  ['specialmobs/albinosilverfish', 'specialmobs:albinosilverfish'],
  ['specialmobs/armoredblaze', 'specialmobs:armoredblaze'],
  ['specialmobs/babycavespider', 'specialmobs:babycavespider'],
  ['specialmobs/babyghast', 'specialmobs:babyghast'],
  ['specialmobs/babyspider', 'specialmobs:babyspider'],
  ['specialmobs/blackberryslime', 'specialmobs:blackberryslime'],
  ['specialmobs/blaze', 'specialmobs:blaze'],
  ['specialmobs/blindingenderman', 'specialmobs:blindingenderman'],
  ['specialmobs/blindingsilverfish', 'specialmobs:blindingsilverfish'],
  ['specialmobs/blueberryslime', 'specialmobs:blueberryslime'],
  ['specialmobs/bouncingmagmacube', 'specialmobs:bouncingmagmacube'],
  ['specialmobs/brutedrowned', 'specialmobs:brutedrowned'],
  ['specialmobs/bruteskeleton', 'specialmobs:bruteskeleton'],
  ['specialmobs/brutewitherskeleton', 'specialmobs:brutewitherskeleton'],
  ['specialmobs/brutezombie', 'specialmobs:brutezombie'],
  ['specialmobs/brutezombifiedpiglin', 'specialmobs:brutezombifiedpiglin'],
  ['specialmobs/caramelslime', 'specialmobs:caramelslime'],
  ['specialmobs/cavespider', 'specialmobs:cavespider'],
  ['specialmobs/cinderblaze', 'specialmobs:cinderblaze'],
  ['specialmobs/conflagrationblaze', 'specialmobs:conflagrationblaze'],
  ['specialmobs/corporealshiftgast', 'specialmobs:corporealshiftghast'],
  ['specialmobs/creeper', 'specialmobs:creeper'],
  ['specialmobs/darkcreeper', 'specialmobs:darkcreeper'],
  ['specialmobs/deathcreeper', 'specialmobs:deathcreeper'],
  ['specialmobs/desertcavespider', 'specialmobs:desertcavespider'],
  ['specialmobs/desertspider', 'specialmobs:desertspider'],
  ['specialmobs/desiccatedsilverfish', 'specialmobs:desiccatedsilverfish'],
  ['specialmobs/dirtcreeper', 'specialmobs:dirtcreeper'],
  ['specialmobs/dominationwitch', 'specialmobs:dominationwitch'],
  ['specialmobs/doomcreeper', 'specialmobs:doomcreeper'],
  ['specialmobs/drowned', 'specialmobs:drowned'],
  ['specialmobs/drowningcreeper', 'specialmobs:drowningcreeper'],
  ['specialmobs/emberblaze', 'specialmobs:emberblaze'],
  ['specialmobs/endercreeper', 'specialmobs:endercreeper'],
  ['specialmobs/enderman', 'specialmobs:enderman'],
  ['specialmobs/fighterghast', 'specialmobs:fighterghast'],
  ['specialmobs/firecavespider', 'specialmobs:firecavespider'],
  ['specialmobs/firecreeper', 'specialmobs:firecreeper'],
  ['specialmobs/firesilverfish', 'specialmobs:firesilverfish'],
  ['specialmobs/fireskeleton', 'specialmobs:fireskeleton'],
  ['specialmobs/firespider', 'specialmobs:firespider'],
  ['specialmobs/firezombie', 'specialmobs:firezombie'],
  ['specialmobs/fishingdrowned', 'specialmobs:fishingdrowned'],
  ['specialmobs/fishingsilverfish', 'specialmobs:fishingsilverfish'],
  ['specialmobs/fishingzombie', 'specialmobs:fishingzombie'],
  ['specialmobs/fishingzombifiedpiglin', 'specialmobs:fishingzombifiedpiglin'],
  ['specialmobs/flameenderman', 'specialmobs:flameenderman'],
  ['specialmobs/flyingcavespider', 'specialmobs:flyingcavespider'],
  ['specialmobs/flyingsilverfish', 'specialmobs:flyingsilverfish'],
  ['specialmobs/flyingspider', 'specialmobs:flyingspider'],
  ['specialmobs/frozendrowned', 'specialmobs:frozendrowned'],
  ['specialmobs/frozenslime', 'specialmobs:frozenslime'],
  ['specialmobs/frozenzombie', 'specialmobs:frozenzombie'],
  ['specialmobs/gatlingskeleton', 'specialmobs:gatlingskeleton'],
  ['specialmobs/gatlingwitherskeleton', 'specialmobs:gatlingwitherskeleton'],
  ['specialmobs/ghast', 'specialmobs:ghast'],
  ['specialmobs/giantdrowned', 'specialmobs:giantdrowned'],
  ['specialmobs/giantskeleton', 'specialmobs:giantskeleton'],
  ['specialmobs/giantspider', 'specialmobs:giantspider'],
  ['specialmobs/giantwitherskeleton', 'specialmobs:giantwitherskeleton'],
  ['specialmobs/giantzombie', 'specialmobs:giantzombie'],
  ['specialmobs/giantzombifiedpiglin', 'specialmobs:giantzombifiedpiglin'],
  ['specialmobs/grapeslime', 'specialmobs:grapeslime'],
  ['specialmobs/gravelcreeper', 'specialmobs:gravelcreeper'],
  ['specialmobs/hardenedmagmacube', 'specialmobs:hardenedmagmacube'],
  ['specialmobs/hellfireblaze', 'specialmobs:hellfireblaze'],
  ['specialmobs/hungrydrowned', 'specialmobs:hungrydrowned'],
  ['specialmobs/hungryzombie', 'specialmobs:hungryzombie'],
  ['specialmobs/hungryzombifiedpiglin', 'specialmobs:hungryzombifiedpiglin'],
  ['specialmobs/huskzombie', 'minecraft:huskzombie'],
  ['specialmobs/icyenderman', 'specialmobs:icyenderman'],
  ['specialmobs/infernoblaze', 'specialmobs:infernoblaze'],
  ['specialmobs/joltblaze', 'specialmobs:joltblaze'],
  ['specialmobs/jumpingcreeper', 'specialmobs:jumpingcreeper'],
  ['specialmobs/kingghast', 'specialmobs:kingghast'],
  ['specialmobs/knightdrowned', 'specialmobs:knightdrowned'],
  ['specialmobs/knightskeleton', 'specialmobs:knightskeleton'],
  ['specialmobs/knightwitherskeleton', 'specialmobs:knightwitherskeleton'],
  ['specialmobs/knightzombifiedpiglin', 'specialmobs:knightzombifiedpiglin'],
  ['specialmobs/lemonslime', 'specialmobs:lemonslime'],
  ['specialmobs/lightningcreeper', 'specialmobs:lightningcreeper'],
  ['specialmobs/lightningenderman', 'specialmobs:lightningenderman'],
  ['specialmobs/madscientistzombie', 'specialmobs:madscientistzombie'],
  ['specialmobs/magmacube', 'specialmobs:magmacube'],
  ['specialmobs/minicreeper', 'specialmobs:minicreeper'],
  ['specialmobs/minienderman', 'specialmobs:minienderman'],
  ['specialmobs/mirageenderman', 'specialmobs:mirageenderman'],
  ['specialmobs/mothercavespider', 'specialmobs:mothercavespider'],
  ['specialmobs/motherspider', 'specialmobs:motherspider'],
  ['specialmobs/ninjaskeleton', 'specialmobs:ninjaskeleton'],
  ['specialmobs/ninjawitherskeleton', 'specialmobs:ninjawitherskeleton'],
  ['specialmobs/palecavespider', 'specialmobs:palecavespider'],
  ['specialmobs/palespider', 'specialmobs:palespider'],
  ['specialmobs/plaguedrowned', 'specialmobs:plaguedrowned'],
  ['specialmobs/plaguezombie', 'specialmobs:plaguezombie'],
  ['specialmobs/plaguezombifiedpiglin', 'specialmobs:plaguezombifiedpiglin'],
  ['specialmobs/poisonsilverfish', 'specialmobs:poisonsilverfish'],
  ['specialmobs/poisonskeleton', 'specialmobs:poisonskeleton'],
  ['specialmobs/poisonspider', 'specialmobs:poisonspider'],
  ['specialmobs/potionslime', 'specialmobs:potionslime'],
  ['specialmobs/puffersilverfish', 'specialmobs:puffersilverfish'],
  ['specialmobs/queenghast', 'specialmobs:queenghast'],
  ['specialmobs/runicenderman', 'specialmobs:runicenderman'],
  ['specialmobs/sandcreeper', 'specialmobs:sandcreeper'],
  ['specialmobs/scopecreeper', 'specialmobs:scopecreeper'],
  ['specialmobs/shadowswitch', 'specialmobs:shadowswitch'],
  ['specialmobs/silverfish', 'specialmobs:silverfish'],
  ['specialmobs/skeleton', 'specialmobs:skeleton'],
  ['specialmobs/skeletoncreeper', 'specialmobs:skeletoncreeper'],
  ['specialmobs/slabghast', 'specialmobs:slabghast'],
  ['specialmobs/slime', 'specialmobs:slime'],
  ['specialmobs/sniperskeleton', 'specialmobs:sniperskeleton'],
  ['specialmobs/sniperwitherskeleton', 'specialmobs:sniperwitherskeleton'],
  ['specialmobs/snowcreeper', 'specialmobs:snowcreeper'],
  ['specialmobs/spider', 'specialmobs:spider'],
  ['specialmobs/spitfireskeleton', 'specialmobs:spitfireskeleton'],
  ['specialmobs/spitfirewitherskeleton', 'specialmobs:spitfirewitherskeleton'],
  ['specialmobs/splittingcreeper', 'specialmobs:splittingcreeper'],
  ['specialmobs/stickymagmacube', 'specialmobs:stickymagmacube'],
  ['specialmobs/strawberryslime', 'specialmobs:strawberryslime'],
  ['specialmobs/strayskeleton', 'specialmobs:strayskeleton'],
  ['specialmobs/thiefenderman', 'specialmobs:thiefenderman'],
  ['specialmobs/toughsilverfish', 'specialmobs:toughsilverfish'],
  ['specialmobs/undeadwitch', 'specialmobs:undeadwitch'],
  ['specialmobs/unholyghast', 'specialmobs:unholyghast'],
  ['specialmobs/vampirezombifiedpiglin', 'specialmobs:vampirezombifiedpiglin'],
  ['specialmobs/volatilemagmacube', 'specialmobs:volatilemagmacube'],
  ['specialmobs/watercavespider', 'specialmobs:watercavespider'],
  ['specialmobs/watermelonslime', 'specialmobs:watermelonslime'],
  ['specialmobs/waterspider', 'specialmobs:waterspider'],
  ['specialmobs/weatheredskeleton', 'specialmobs:weatheredskeleton'],
  ['specialmobs/webcavespider', 'specialmobs:webcavespider'],
  ['specialmobs/webspider', 'specialmobs:webspider'],
  ['specialmobs/wildfireblaze', 'specialmobs:wildfireblaze'],
  ['specialmobs/wildswitch', 'specialmobs:wildswitch'],
  ['specialmobs/windwitch', 'specialmobs:windwitch'],
  ['specialmobs/witch', 'specialmobs:witch'],
  ['specialmobs/witchcavespider', 'specialmobs:witchcavespider'],
  ['specialmobs/witchspider', 'specialmobs:witchspider'],
  ['specialmobs/witherskeleton', 'specialmobs:witherskeleton'],
  ['specialmobs/zombie', 'specialmobs:zombie'],
  ['specialmobs/zombifiedpiglin', 'specialmobs:zombifiedpiglin'],
  ['spectrum/egg_laying_wooly_pig', 'spectrum:egg_laying_wooly_pig'],
  ['spectrum/eraser', 'spectrum:eraser'],
  ['spectrum/kindling', 'spectrum:kindling'],
  ['spectrum/lizard', 'spectrum:lizard'],
  ['spectrum/preservation_turret', 'spectrum:preservation_turret'],
  ['strawgolem/strawgolem', 'strawgolem:strawgolem'],
  ['strawgolem/strawngolem', 'strawgolem:strawnggolem'],
  ['sullysmod/lanternfish', 'sullysmod:lanternfish'],
  ['sullysmod/tortoise', 'sullysmod:tortoise'],
  ['supplementaries/supplementaries_red_merchant', 'supplementaries:red_merchant'],
  ['sushigocrafting/shrimp', 'sushigocrafting:shrimp'],
  ['sushigocrafting/tuna', 'sushigocrafting:tuna'],
  ['tconstruct/earth_slime', 'tconstruct:earth_slime'],
  ['tconstruct/ender_slime', 'tconstruct:ender_slime'],
  ['tconstruct/sky_slime', 'tconstruct:sky_slime'],
  ['tconstruct/terracube', 'tconstruct:terracube'],
  ['thermal/basalz', 'thermal:basalz'],
  ['thermal/blitz', 'thermal:blitz'],
  ['thermal/blizz', 'thermal:blizz'],
  ['tolerable_creepers/tolerable_creepers_moonflower_creepie', 'tolerable_creepers:creepie'],
  ['twilightforest/alpha_yeti', 'twilightforest:alpha_yeti'],
  ['twilightforest/armored_giant', 'twilightforest:armored_giant'],
  ['twilightforest/bighorn_sheep', 'twilightforest:bighorn_sheep'],
  ['twilightforest/blockchain_goblin', 'twilightforest:blockchain_goblin'],
  ['twilightforest/boar', 'twilightforest:boar'],
  ['twilightforest/carminite_broodling', 'twilightforest:carminite_broodling'],
  ['twilightforest/carminite_ghastguard', 'twilightforest:carminite_ghastguard'],
  ['twilightforest/carminite_ghastling', 'twilightforest:carminite_ghastling'],
  ['twilightforest/carminite_golem', 'twilightforest:carminite_golem'],
  ['twilightforest/death_tome', 'twilightforest:death_tome'],
  ['twilightforest/deer', 'twilightforest:deer'],
  ['twilightforest/dwarf_rabbit', 'twilightforest:dwarf_rabbit'],
  ['twilightforest/fire_beetle', 'twilightforest:fire_beetle'],
  ['twilightforest/giant_miner', 'twilightforest:giant_miner'],
  ['twilightforest/hedge_spider', 'twilightforest:hedge_spider'],
  ['twilightforest/helmet_crab', 'twilightforest:helmet_crab'],
  ['twilightforest/hostile_wolf', 'twilightforest:hostile_wolf'],
  ['twilightforest/hydra', 'twilightforest:hydra'],
  ['twilightforest/king_spider', 'twilightforest:king_spider'],
  ['twilightforest/knight_phantom', 'twilightforest:knight_phantom'],
  ['twilightforest/kobold', 'twilightforest:kobold'],
  ['twilightforest/lich', 'twilightforest:lich'],
  ['twilightforest/lower_goblin_knight', 'twilightforest:lower_goblin_knight'],
  ['twilightforest/maze_slime', 'twilightforest:maze_slime'],
  ['twilightforest/minoshroom', 'twilightforest:minoshroom'],
  ['twilightforest/minotaur', 'twilightforest:minotaur'],
  ['twilightforest/mist_wolf', 'twilightforest:mist_wolf'],
  ['twilightforest/mosquito_swarm', 'twilightforest:mosquito_swarm'],
  ['twilightforest/naga', 'twilightforest:naga'],
  ['twilightforest/penguin', 'twilightforest:penguin'],
  ['twilightforest/pinch_beetle', 'twilightforest:pinch_beetle'],
  ['twilightforest/quest_ram', 'twilightforest:quest_ram'],
  ['twilightforest/raven', 'twilightforest:raven'],
  ['twilightforest/redcap', 'twilightforest:redcap'],
  ['twilightforest/redcap_sapper', 'twilightforest:redcap_sapper'],
  ['twilightforest/skeleton_druid', 'twilightforest:skeleton_druid'],
  ['twilightforest/slime_beetle', 'twilightforest:slime_beetle'],
  ['twilightforest/snow_guardian', 'twilightforest:snow_guardian'],
  ['twilightforest/snow_queen', 'twilightforest:snow_queen'],
  ['twilightforest/squirrel', 'twilightforest:squirrel'],
  ['twilightforest/stable_ice_core', 'twilightforest:stable_ice_core'],
  ['twilightforest/swarm_spider', 'twilightforest:swarm_spider'],
  ['twilightforest/tiny_bird', 'twilightforest:tiny_bird'],
  ['twilightforest/towerwood_borer', 'twilightforest:towerwood_borer'],
  ['twilightforest/troll', 'twilightforest:troll'],
  ['twilightforest/unstable_ice_core', 'twilightforest:unstable_ice_core'],
  ['twilightforest/upper_goblin_knight', 'twilightforest:upper_goblin_knight'],
  ['twilightforest/ur_ghast', 'twilightforest:ur_ghast'],
  ['twilightforest/winter_wolf', 'twilightforest:winter_wolf'],
  ['twilightforest/wraith', 'twilightforest:wraith'],
  ['twilightforest/yeti', 'twilightforest:yeti'],
  ['undergarden/undergarden_brute', 'undergarden:brute'],
  ['undergarden/undergarden_dweller', 'undergarden:dweller'],
  ['undergarden/undergarden_forgotten_guardian', 'undergarden:forgotten_guardian'],
  ['undergarden/undergarden_gloomper', 'undergarden:gloomper'],
  ['undergarden/undergarden_gwib', 'undergarden:gwib'],
  ['undergarden/undergarden_gwibling', 'undergarden:gwibling'],
  ['undergarden/undergarden_mog', 'undergarden:mog'],
  ['undergarden/undergarden_muncher', 'undergarden:muncher'],
  ['undergarden/undergarden_nargoyle', 'undergarden:nargoyle'],
  ['undergarden/undergarden_rotbeast', 'undergarden:rotbeast'],
  ['undergarden/undergarden_rotling', 'undergarden:rotling'],
  ['undergarden/undergarden_rotwalker', 'undergarden:rotwalker'],
  ['undergarden/undergarden_scintling', 'undergarden:scintling'],
  ['undergarden/undergarden_sploogie', 'undergarden:sploogie'],
  ['undergarden/undergarden_stoneborn', 'undergarden:stoneborn'],
  ['waddles/adelie_penguin', 'waddles:adelie_penguin'],
  ['yungs_sex_mod/ice_cube', 'yungscavebiomes:ice_cube'],
  ['yungs_sex_mod/sandsnapper', 'yungscavebiomes:sand_snapper'],
]

ServerEvents.generateData('last', event => {
  // 1) 自定义掉落
  Object.keys(SPIRIT_DROPS).forEach(entityId => {
    const data = SPIRIT_DROPS[entityId]
    const path = entityId.split(':')[1]
    event.json('malum:spirit_data/entity/cataclysm/' + path, {
      registry_name: entityId,
      primary_type: data.primary,
      spirits: data.spirits.map(entry => {
        return { spirit: entry[0], count: entry[1] }
      })
    })
  })

  // 2) 覆盖 Malum 自带的掉落文件为 no_spirits
  MALUM_DEFAULT_DROPS.forEach(entry => {
    event.json('malum:spirit_data/entity/' + entry[0], {
      registry_name: entry[1],
      no_spirits: true
    })
  })

  // 3) 其余所有实体也关闭（含类别默认）
  if (DISABLE_DEFAULT_DROPS) {
    $BuiltInRegistries.ENTITY_TYPE.keySet().forEach(key => {
      const id = key.toString()
      if (SPIRIT_DROPS[id]) return
      event.json('malum:spirit_data/entity/cdp2_no_spirits/' + key.getNamespace() + '/' + key.getPath(), {
        registry_name: id,
        no_spirits: true
      })
    })
  }
})
