ServerEvents.recipes(event =>{
    const prefix = "cdp2:recipes/naturesaura/animal_spawner/"

    const recipes = [
        {
            "entity":"minecraft:skeleton",
            "inputs":[
                'minecraft:egg',
                'minecraft:skeleton_skull',
                'naturesaura:birth_spirit'
            ],
            "aura":0,
            "time":10,
            "id":"skeleton"
        },
        {
            "entity":"minecraft:fox",
            "inputs":[
                'minecraft:sweet_berries',
                'naturesaura:birth_spirit'
            ],
            "aura":0,
            "time":10,
            "id":"fox"
        },
        {
            "entity":'minecraft:cow',
            "inputs":[
                'minecraft:leather',
                'industrialforegoing:pink_slime_ingot',
                'naturesaura:birth_spirit'
            ],
            "aura":0,
            "time":10,
            "id":"cow"
        },
        {
            "entity":'minecraft:wither',
            "inputs":[
                'occultism:iesnium_block',
                'minecraft:soul_sand',
                'minecraft:wither_skeleton_skull',
                'naturesaura:birth_spirit'
            ],
            "aura":0,
            "time":10,
            "id":"wither"
        },
        {
            "entity":'minecraft:ghast',
            "inputs":[
                'naturesaura:birth_spirit',
                'minecraft:ghast_tear',
                'minecraft:sculk'
            ],
            "aura":0,
            "time":10,
            "id":"ghast"
        },
        {
            "entity":'minecraft:ender_dragon',
            "inputs":[
                'naturesaura:birth_spirit',
                'ifeu:dragon_star_block'
            ],
            "aura":90000,
            "time":100,
            "id":"ender_dragon"
        },
        {
            "entity":'occultism:afrit_wild',
            "inputs":[
                'naturesaura:birth_spirit',
                'jdte:life_apple',
                'occultism:iesnium_ingot'
            ],
            "aura":90000,
            "time":100,
            "id":"afrit_wild"
        },
        {
            "entity":'minecraft:evoker',
            "inputs":[
                'naturesaura:birth_spirit',
                'minecraft:emerald'
            ],
            "aura":90000,
            "time":100,
            "id":"evoker"
        },
        {
            "entity":'minecraft:shulker',
            "inputs":[
                'naturesaura:birth_spirit',
                'naturesaura:depth_ingot'
            ],
            "aura":90000,
            "time":100,
            "id":"shulker"
        },
        {
            "entity":'minecraft:pig',
            "inputs":[
                'naturesaura:birth_spirit',
                'minecraft:pink_wool',
                'mekanism_extras:alloy_spectrum'
            ],
            "aura":90000,
            "time":100,
            "id":"pig"
        }
    ]

    recipes.forEach(recipe =>{
        event.recipes.naturesaura.animal_spawner(recipe.entity,recipe.inputs,recipe.aura,recipe.time).id(prefix + recipe.id)
    })
})